// Demo document — exercises the pipeline end to end. Default-exports the root element the
// generator renders; `title` becomes the HTML <title>. Grows as components land in later tasks.

import { Doc } from '../components/Doc.js';
import { Cover } from '../components/Cover.js';
import { Section } from '../components/Section.js';
import { Footer } from '../components/Footer.js';

export const title = 'Harvest × Bloom Parity';

export default (
  <Doc>
    <Cover
      eyebrow="Design system · 2026-09-10"
      title="Harvest × Bloom Parity"
      lede="A demonstration document rendered by the React builder to standalone HTML and to PDF, in both light and dark themes."
      chips={['Theme · designed', 'React 18', 'native Tailwind']}
    />

    <Section
      eyebrow="Category by category"
      title="The pipeline spine"
      deck="This first increment proves the end-to-end path: hand-written JSX becomes an HTML source of truth, and a headless-Chrome print turns that into a PDF."
    >
      <p>
        Everything on the page is colored only through the typed token module, so a single palette
        swap re-themes the whole document. The eyebrow above sits in the accent role; this body copy
        is the base ink on the page ground.
      </p>
      <p>
        Later increments hang the rest of the component library — callouts, badges, tables, compare
        cards, panels, phases, flow lanes, code blocks, and diagrams — off this same spine.
      </p>
    </Section>

    <Footer
      lines={[
        'Generated by @docsmith/builder from src/docs/demo.tsx',
        'pipeline · JSX → HTML (renderToStaticMarkup) → PDF (headless Chrome)',
        'reference · github.com/dashworthy/docsmith',
      ]}
    />
  </Doc>
);
